FROM node:14.17.0-alpine3.13 as api

# Create app directory
WORKDIR /usr/src/app

COPY . ./

# Install app dependencies
RUN yarn cache clean && yarn install

EXPOSE 4000

## THE LIFE SAVER
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD /wait && yarn start
