version: "3.7"

services:
    server_web_back:
        container_name: server_web_back
        hostname: server_web_back
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile.prod
        environment:
            WAIT_HOSTS: ${INSTANCE_DB}:27017
        ports:
            - 4000:4000
#         networks:
#             - nginx_nginx_network

# networks:
#     nginx_nginx_network:
#         external: true