export const USER_LOADING = "USER_LOADING";
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
export const USER_ERROR = "USER_ERROR";
export const USER_UPDATE = "USER_UPDATE";
export const USER_LOGOUT = "USER_LOGOUT";

export const DISCUSSION_LOADING = "DISCUSSION_LOADING";
export const DISCUSSION_ERROR = "DISCUSSION_ERROR";
export const GET_ALL_DISCUSSIONS = "GET_ALL_DISCUSSIONS";
export const CREATE_DISCUSSION = "CREATE_DISCUSSION";
export const UPDATE_DISCUSSION = "UPDATE_DISCUSSION";
export const DELETE_DISCUSSION = "DELETE_DISCUSSION";


export const ZONE_LOADING = "ZONE_LOADING";
export const ZONE_ERROR = "ZONE_ERROR";
export const CREATE_ZONE = "CREATE_ZONE";
export const GET_ALL_ZONES = "GET_ALL_ZONES";
export const SET_MY_ZONE = "SET_MY_ZONE";

export const MESSAGE_LOADING = "MESSAGE_LOADING";
export const MESSAGE_ERROR = "MESSAGE_ERROR";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const REPORT_MESSAGE = "REPORT_MESSAGE";
export const GET_MODERATION_MESSAGE = "GET_MODERATION_MESSAGE";
export const UPDATE_MODERATION_VOTE_MESSAGE = "UPDATE_MODERATION_VOTE_MESSAGE";
